FROM python:3.11-slim

# Docker client
ENV COMPOSE_VERSION=2.14.0

COPY --from=library/docker /usr/local/bin /usr/local/bin

ADD https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-linux-x86_64 /root/.docker/cli-plugins/docker-compose

RUN chmod +x ~/.docker/cli-plugins/docker-compose

ENV CERTBOT_DNS_LEXICON_PLUGIN_VERSION=1.0.0

COPY generate_certs.py /usr/local/bin/generate-certs
COPY generate_ovh_key.py /usr/local/bin/generate-ovh-key
COPY requirements.txt .

RUN pip install pip setuptools --upgrade --no-cache-dir && \
    pip install -r requirements.txt --no-cache-dir \
    https://github.com/MaciejSzczurek/certbot-dns-lexicon/releases/download/v${CERTBOT_DNS_LEXICON_PLUGIN_VERSION}/certbot_dns_lexicon-${CERTBOT_DNS_LEXICON_PLUGIN_VERSION}-py3-none-any.whl && \
    chmod +x /usr/local/bin/generate-certs /usr/local/bin/generate-ovh-key && \
    rm -rf requirements.txt /tmp/*
