on:
  workflow_dispatch:
  push:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker buildx build --pull -t maciejszczurek/generate-certs .
